//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkobazar.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "firstname must not be empty !")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "lastname must not be empty !")]
        public string lastname { get; set; }

        [Required(ErrorMessage = "address must not be empty !")]
        public string address { get; set; }

        [Required(ErrorMessage = "phone must not be empty !")]
        public string phone { get; set; }

        [Required(ErrorMessage = "pesel must not be empty !")]
        public string pesel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
